[build]
builder = "nixpacks"

[deploy]
startCommand = "python server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8002" }
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"