services:
  - type: web
    name: hassaniya-normalizer
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -e .
    startCommand: hassy-web
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    plan: free
    region: oregon
    healthCheckPath: /